[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "phantombunch"
version = "2023.11.0"
authors = [
  { name="Marijan Beg", email="m.beg@imperial.ac.uk" },
]
description = "A Python package for generating random personal data."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD-3-Clause License",
    "Operating System :: OS Independent",
]
dependencies = [
    "faker >= 19.0.0",
    "pycountry >= 22.3.5",
    "pandas >= 2.0.0",
]

[project.urls]
"Homepage" = "https://github.com/marijanbeg/phantombunch"

[tool.ruff]
ignore-init-module-imports = true