name: ruff

on: [push, pull_request]

jobs:
  ruff:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    
      - name: Ruff
        run: pipx run ruff check --output-format=github .
