name: ruff

on: [push, pull_request]

jobs:
  ruff:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install ruff
        run: pipx install ruff
    
      - name: Ruff
        run: ruff check --output-format=github .