name: tests

on: [push, pull_request]

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pipx install poetry

      - name: Install
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install --no-interaction

      - name: Venv info
        run: poetry env info

      - name: Pytest
        run: poetry run pytest
