name: tests

on: [push, pull_request]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install
        run: poetry install

      - name: Test with pytest
        run: pytest